apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: kube-scheduler
    version: v0.1.0
  name: kube-scheduler
  namespace: kube-system
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 1
    targetPort: 1
  selector:
    harbor-app: kube-scheduler
