apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: kube2sky
    version: v0.1.0
  name: kube2sky
  namespace: kube-system
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  selector:
    harbor-app: kube2sky
