apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: kuryr-libnetwork
    version: v0.1.0
  name: kuryr-libnetwork
  namespace: node-neutron
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 1
    targetPort: 1
  selector:
    harbor-app: kuryr-libnetwork
