apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-neutron-api
    version: v0.1.0
  name: undercloud-neutron-api
  namespace: node-neutron
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 9696
    targetPort: 9696
    protocol: TCP
    name: neutron
  selector:
    harbor-app: undercloud-neutron-api
