apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glance
  name: os-glance
  namespace: os-glance
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 9292
    protocol: TCP
    name: https
  selector:
    openstack-app: glance
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glance-registry
  name: os-glance-registry
  namespace: os-glance
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 9191
    protocol: TCP
    name: https
  selector:
    openstack-app: glance-registry
