apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: murano
  name: os-murano
  namespace: os-murano
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8082
    protocol: TCP
    name: https
  selector:
    openstack-app: murano
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: murano-engine
  name: murano-engine
  namespace: os-murano
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: murano-engine
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: murano
  name: os-murano-messaging
  namespace: os-murano
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5672
    targetPort: 5671
    protocol: TCP
    name: rabbitmq
  selector:
    openstack-app: murano-messaging
