apiVersion: v1
kind: Secret
metadata:
  name: cinder-manager
  namespace: os-cinder
type: Opaque
data:
  kube-endpoint: {{KUBE_ENDPOINT}}
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  keystone-admin-token: {{KEYSTONE_ADMIN_TOKEN}}
  keystone-admin-user: {{KEYSTONE_ADMIN_USER}}
  keystone-admin-project: {{KEYSTONE_ADMIN_PROJECT}}
  keystone-admin-password: {{KEYSTONE_ADMIN_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
  cinder-db-name: {{CINDER_DB_NAME}}
  cinder-db-user: {{CINDER_DB_USER}}
  cinder-db-password: {{CINDER_DB_PASSWORD}}
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: cinder-manager
    version: v0.1.0
  name: cinder-manager
  namespace: os-cinder
spec:
  template:
    metadata:
      labels:
        openstack-app: cinder-manager
        version: v0.1.0
      name: cinder-manager
      namespace: os-cinder
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: cinder-manager
          image:  docker.io/port/cinder-manager:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: ipa-config
              mountPath: /etc/ipa/default.conf
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config
          secret:
            secretName: cinder-manager
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: ipa-config
          hostPath:
            path: /etc/ipa/default.conf
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker-ipa.sock
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder
  namespace: os-cinder
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
  cinder-db-name: {{CINDER_DB_NAME}}
  cinder-db-user: {{CINDER_DB_USER}}
  cinder-db-password: {{CINDER_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: cinder
    version: v0.1.0
  name: cinder
  namespace: os-cinder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: cinder
        version: v0.1.0
      name: cinder
      namespace: os-cinder
    spec:
      nodeSelector:
        openstack-cinder: 'true'
        arch: 'x86'
      containers:
        - name: cinder
          image: docker.io/port/cinder-api:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
        - name: cinder-tls
          image: docker.io/port/haproxy-ssl-terminator:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
            - name: LOCAL_HTTP_PORT
              value: "18776"
            - name: PUBLISH_HTTPS_PORT
              value: "8776"
          ports:
          - containerPort: 8776
            name: https
            protocol: TCP
          volumeMounts:
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: cinder
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: cinder-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-scheduler
  namespace: os-cinder
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
  cinder-db-name: {{CINDER_DB_NAME}}
  cinder-db-user: {{CINDER_DB_USER}}
  cinder-db-password: {{CINDER_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: cinder-scheduler
    version: v0.1.0
  name: cinder-scheduler
  namespace: os-cinder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: cinder-scheduler
        version: v0.1.0
      name: cinder-scheduler
      namespace: os-cinder
    spec:
      nodeSelector:
        openstack-cinder: 'true'
        arch: 'x86'
      containers:
        - name: cinder-scheduler
          image: docker.io/port/cinder-scheduler:latest
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: cinder-scheduler
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-volume
  namespace: os-cinder
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
  cinder-db-name: {{CINDER_DB_NAME}}
  cinder-db-user: {{CINDER_DB_USER}}
  cinder-db-password: {{CINDER_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: cinder-volume-glusterfs
    version: v0.1.0
  name: cinder-volume-glusterfs
  namespace: os-cinder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: cinder-volume-glusterfs
        version: v0.1.0
      name: cinder-volume-glusterfs
      namespace: os-cinder
    spec:
      nodeSelector:
        openstack-cinder: 'true'
        arch: 'x86'
      containers:
        - name: cinder-volume-glusterfs
          image: docker.io/port/cinder-volume-glusterfs:latest
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: lib-modules
              mountPath: "/lib/modules"
              readOnly: true
            - name: dev
              mountPath: "/dev"
              readOnly: false
            - name: cinder-data
              mountPath: "/opt/data"
              readOnly: false
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      volumes:
        - name: os-config
          secret:
            secretName: cinder-volume
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: cinder-data
          emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: cinder-backup
    version: v0.1.0
  name: cinder-backup
  namespace: os-cinder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: cinder-backup
        version: v0.1.0
      name: cinder-backup
      namespace: os-cinder
    spec:
      nodeSelector:
        openstack-cinder: 'true'
        cinder-backend: 'lvm'
        arch: 'x86'
      containers:
        - name: cinder-backup
          image: docker.io/port/cinder-backup:latest
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: lib-modules
              mountPath: "/lib/modules"
              readOnly: true
            - name: run-lvm
              mountPath: "/run/lvm"
              readOnly: false
            - name: dev
              mountPath: "/dev"
              readOnly: false
            - name: cinder-data
              mountPath: "/opt/data"
              readOnly: false
            - name: var-lib-cinder-volumes
              mountPath: "/var/lib/cinder/volumes"
              readOnly: false
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      volumes:
        - name: os-config
          secret:
            secretName: cinder-volume
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run-lvm
          hostPath:
            path: /run/lvm
        - name: dev
          hostPath:
            path: /dev
        - name: cinder-data
          emptyDir: {}
        - name: var-lib-cinder-volumes
          hostPath:
            path: /var/lib/cinder/volumes
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    openstack-app: cinder-volume-lvm
    version: v0.1.0
  name: cinder-volume-lvm
  namespace: os-cinder
spec:
  template:
    metadata:
      labels:
        openstack-app: cinder-volume-lvm
        version: v0.1.0
      name: cinder-volume-lvm
      namespace: os-cinder
    spec:
      nodeSelector:
        openstack-cinder: 'true'
        cinder-backend: 'lvm'
        arch: 'x86'
      containers:
        - name: cinder-volume-lvm
          image: docker.io/port/cinder-volume-lvm:latest
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: lib-modules
              mountPath: "/lib/modules"
              readOnly: true
            - name: run-lvm
              mountPath: "/run/lvm"
              readOnly: false
            - name: dev
              mountPath: "/dev"
              readOnly: false
            - name: cinder-data
              mountPath: "/opt/data"
              readOnly: false
            - name: var-lib-cinder-volumes
              mountPath: "/var/lib/cinder/volumes"
              readOnly: false
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      volumes:
        - name: os-config
          secret:
            secretName: cinder-volume
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run-lvm
          hostPath:
            path: /run/lvm
        - name: dev
          hostPath:
            path: /dev
        - name: cinder-data
          emptyDir: {}
        - name: var-lib-cinder-volumes
          hostPath:
            path: /var/lib/cinder/volumes
