apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glusterfs
  name: os-glusterfs
  namespace: os-glusterfs
spec:
  sessionAffinity: 'ClientIP'
  clusterIP: "None"
  ports:
  - port: 111
    targetPort: 111
    protocol: TCP
    name: portmapper
  - port: 2048
    targetPort: 2048
    protocol: TCP
    name: nfs
  - port: 24007
    targetPort: 24007
    protocol: TCP
    name: glusterd
  - port: 38465
    targetPort: 38465
    protocol: TCP
    name: gluster-nfs-1
  - port: 38466
    targetPort: 38466
    protocol: TCP
    name: gluster-nfs-2
  - port: 38467
    targetPort: 38467
    protocol: TCP
    name: gluster-nfs-3
  selector:
    openstack-app: glusterfs
