apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: manila
  name: os-manila
  namespace: os-manila
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8786
    protocol: TCP
    name: https
  selector:
    openstack-app: manila
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: manila-scheduler
  name: manila-scheduler
  namespace: os-manila
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: manila-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: manila-share
  name: manila-share
  namespace: os-manila
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: manila-share
