apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: etcd-core
    version: v0.1.0
  name: etcd-core
  namespace: node-etcd
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
    name: etcd
  - port: 2380
    targetPort: 2380
    protocol: TCP
    name: peers
  selector:
    harbor-app: etcd-core
