#!/bin/bash

if [ -s /run/local-container/exit_code ] ; then
	exit_code=$( cat /run/local-container/exit_code )
	if [ -e /run/local-container/exit-on-finished ] || ! [ "$exit_code" == 0 ] ; then
		systemctl poweroff
	fi
fi
exit
