apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 8888
    name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-storage
  labels:
    app: {{OPENSTACK_COMPONENT}}-storage
spec:
  type: ClusterIP
  ports:
  - port: 1
  clusterIP: None
  selector:
    app: {{OPENSTACK_COMPONENT}}-storage-rc
