apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
      name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    spec:
      nodeSelector:
        swift-proxy: 'true'
      containers:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/swift-proxy-server:{{OS_RELEASE}}
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}.{{OS_DOMAIN}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          securityContext:
            privileged: false
        - name: {{OPENSTACK_COMPONENT}}-memcached
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/memcached:{{OS_RELEASE}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"
          securityContext:
            privileged: false
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
