apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: database
  name: os-database
  namespace: os-database
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    openstack-app: database
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: database-mongodb
  name: os-mongodb
  namespace: os-database
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    openstack-app: database-mongodb
