apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-sni
  labels:
    app: {{OPENSTACK_COMPONENT}}-sni
spec:
  type: ClusterIP
  ports:
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-sni-rc
