apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}
spec:
  ports:
  - port: 80
    protocol: TCP
  - port: 443
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-rc
