apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-rc
      name: {{OPENSTACK_COMPONENT}}
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/accounts-portal:{{OS_RELEASE}}
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}.{{OS_DOMAIN}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: {{OPENSTACK_COMPONENT}}-storage
              mountPath: "/var/lib/freeipa_community_portal"
          securityContext:
            privileged: true
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}
        - name: {{OPENSTACK_COMPONENT}}-storage
