apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
      name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/cinder-api:{{OS_RELEASE}}
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}.{{OS_DOMAIN}}
          ports:
            - containerPort: 8776
              name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
              protocol: TCP
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{OPENSTACK_COMPONENT}}-memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-scheduler-rc
      name: {{OPENSTACK_COMPONENT}}-scheduler
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-scheduler
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/cinder-scheduler:{{OS_RELEASE}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
