apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-nova-compute
    version: v0.1.0
  name: undercloud-nova-compute
  namespace: node-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 1
    targetPort: 1
  selector:
    harbor-app: undercloud-nova-compute
