apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-ovn-northbound-db
    version: v0.1.0
  name: ovn-northbound-db
  namespace: node-ovn
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 6641
    targetPort: 6641
    protocol: TCP
    name: ovsdb
  selector:
    harbor-app: undercloud-ovn-northbound-db
