apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ipsilon-server
  name: os-ipsilon
  namespace: os-ipsilon
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 4143
    protocol: TCP
    name: https
  selector:
    openstack-app: ipsilon-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ipsilon-db
  name: ipsilon-db
  namespace: os-ipsilon
spec:
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: psql
  selector:
    openstack-app: ipsilon-db
