apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-memcached
    version: v0.1.0
  name: undercloud-memcached
  namespace: node-memcached
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
    name: memcached
  selector:
    harbor-app: undercloud-memcached
