apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-horizon
    version: v0.1.0
  name: undercloud-horizon
  namespace: node-horizon
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    harbor-app: undercloud-horizon
