apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cloudkitty
  name: os-cloudkitty
  namespace: os-cloudkitty
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8888
    protocol: TCP
    name: https
  selector:
    openstack-app: cloudkitty
