apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: os-tenant-proxy
  labels:
    app: os-tenant-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: os-tenant-proxy
    protocol: TCP
  selector:
    app: os-tenant-proxy-rc
---
apiVersion: v1
kind: Service
metadata:
  name: os-web-proxy
  labels:
    app: os-web-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    nodePort: 80
    name: os-web-proxy
    protocol: TCP
  selector:
    app: os-web-proxy-rc
