apiVersion: v1
kind: Secret
metadata:
  name: manila-manager
  namespace: os-manila
type: Opaque
data:
  kube-endpoint: {{KUBE_ENDPOINT}}
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  keystone-admin-token: {{KEYSTONE_ADMIN_TOKEN}}
  keystone-admin-user: {{KEYSTONE_ADMIN_USER}}
  keystone-admin-project: {{KEYSTONE_ADMIN_PROJECT}}
  keystone-admin-password: {{KEYSTONE_ADMIN_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  manila-keystone-user: {{MANILA_KEYSTONE_USER}}
  manila-keystone-password: {{MANILA_KEYSTONE_PASSWORD}}
  manila-db-name: {{MANILA_DB_NAME}}
  manila-db-user: {{MANILA_DB_USER}}
  manila-db-password: {{MANILA_DB_PASSWORD}}
  nova-keystone-user: {{NOVA_KEYSTONE_USER}}
  nova-keystone-password: {{NOVA_KEYSTONE_PASSWORD}}
  neutron-keystone-user: {{NEUTRON_KEYSTONE_USER}}
  neutron-keystone-password: {{NEUTRON_KEYSTONE_PASSWORD}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: manila-manager
    version: v0.1.0
  name: manila-manager
  namespace: os-manila
spec:
  template:
    metadata:
      labels:
        openstack-app: manila-manager
        version: v0.1.0
      name: manila-manager
      namespace: os-manila
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: manila-manager
          image:  docker.io/port/manila-manager:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/ipa/ca.crt
              readOnly: true
            - name: ipa-config
              mountPath: /etc/ipa/default.conf
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config
          secret:
            secretName: manila-manager
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: ipa-config
          hostPath:
            path: /etc/ipa/default.conf
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker-ipa.sock
---
apiVersion: v1
kind: Secret
metadata:
  name: manila
  namespace: os-manila
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  manila-keystone-user: {{MANILA_KEYSTONE_USER}}
  manila-keystone-password: {{MANILA_KEYSTONE_PASSWORD}}
  manila-db-name: {{MANILA_DB_NAME}}
  manila-db-user: {{MANILA_DB_USER}}
  manila-db-password: {{MANILA_DB_PASSWORD}}
  nova-keystone-user: {{NOVA_KEYSTONE_USER}}
  nova-keystone-password: {{NOVA_KEYSTONE_PASSWORD}}
  neutron-keystone-user: {{NEUTRON_KEYSTONE_USER}}
  neutron-keystone-password: {{NEUTRON_KEYSTONE_PASSWORD}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: manila
    version: v0.1.0
  name: manila
  namespace: os-manila
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: manila
        version: v0.1.0
      name: manila
      namespace: os-manila
    spec:
      nodeSelector:
        openstack-manila: 'true'
        arch: 'x86'
      containers:
        - name: manila-api
          image: docker.io/port/manila-api:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssh
              mountPath: "/etc/os-ssh"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
        - name: manila-memcached
          image: docker.io/port/system-memcached:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "64Mi"
              cpu: "0.2"
          securityContext:
            privileged: false
        - name: manila-tls
          image: docker.io/port/haproxy-ssl-terminator:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
            - name: LOCAL_HTTP_PORT
              value: "8011"
            - name: PUBLISH_HTTPS_PORT
              value: "8786"
          ports:
          - containerPort: 8786
            name: https
            protocol: TCP
          volumeMounts:
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: manila
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: manila-ssl-secret
        - name: os-ssh
          secret:
            secretName: manila-ssh-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: manila-scheduler
  namespace: os-manila
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  manila-keystone-user: {{MANILA_KEYSTONE_USER}}
  manila-keystone-password: {{MANILA_KEYSTONE_PASSWORD}}
  manila-db-name: {{MANILA_DB_NAME}}
  manila-db-user: {{MANILA_DB_USER}}
  manila-db-password: {{MANILA_DB_PASSWORD}}
  nova-keystone-user: {{NOVA_KEYSTONE_USER}}
  nova-keystone-password: {{NOVA_KEYSTONE_PASSWORD}}
  neutron-keystone-user: {{NEUTRON_KEYSTONE_USER}}
  neutron-keystone-password: {{NEUTRON_KEYSTONE_PASSWORD}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: manila-scheduler
    version: v0.1.0
  name: manila-scheduler
  namespace: os-manila
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: manila-scheduler
        version: v0.1.0
      name: manila-scheduler
      namespace: os-manila
    spec:
      nodeSelector:
        openstack-manila: 'true'
        arch: 'x86'
      containers:
        - name: manila-scheduler
          image: docker.io/port/manila-scheduler:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssh
              mountPath: "/etc/os-ssh"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: manila-scheduler
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssh
          secret:
            secretName: manila-ssh-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: manila-share
  namespace: os-manila
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  manila-keystone-user: {{MANILA_KEYSTONE_USER}}
  manila-keystone-password: {{MANILA_KEYSTONE_PASSWORD}}
  manila-db-name: {{MANILA_DB_NAME}}
  manila-db-user: {{MANILA_DB_USER}}
  manila-db-password: {{MANILA_DB_PASSWORD}}
  nova-keystone-user: {{NOVA_KEYSTONE_USER}}
  nova-keystone-password: {{NOVA_KEYSTONE_PASSWORD}}
  neutron-keystone-user: {{NEUTRON_KEYSTONE_USER}}
  neutron-keystone-password: {{NEUTRON_KEYSTONE_PASSWORD}}
  cinder-keystone-user: {{CINDER_KEYSTONE_USER}}
  cinder-keystone-password: {{CINDER_KEYSTONE_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: manila-share
    version: v0.1.0
  name: manila-share
  namespace: os-manila
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: manila-share
        version: v0.1.0
      name: manila-share
      namespace: os-manila
    spec:
      nodeSelector:
        openstack-manila: 'true'
        neutron-services: 'true'
        arch: 'x86'
      containers:
        - name: manila-share
          image: docker.io/port/manila-share:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssh
              mountPath: "/etc/os-ssh"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: var-run-netns
              mountPath: /var/run/netns
              readOnly: false
            - name: var-run-openvswitch
              mountPath: /var/run/openvswitch
              readOnly: false
            - name: lib-modules
              mountPath: "/lib/modules"
              readOnly: true
            - name: dev
              mountPath: "/dev"
              readOnly: false
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      volumes:
        - name: os-config
          secret:
            secretName: manila-share
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssh
          secret:
            secretName: manila-ssh-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: var-run-netns
          hostPath:
            path: /var/run/netns
        - name: var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
