#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

BASE_URL=${DIB_EPEL_MIRROR:-https://dl.fedoraproject.org/pub/epel}
case "$DISTRO_NAME" in
    rhel7|centos7)
        RELEASE=7
        RPM_URL=$BASE_URL/$RELEASE/x86_64/e/
        ;;
    *)
        echo "$DISTRO_NAME is not supported"
        exit 1
        ;;
esac


cat > /etc/yum.repos.d/elrepo-kernel.repo <<EOF
[elrepo-kernel]
name=ELRepo.org Community Enterprise Linux Kernel Repository - el7
baseurl=http://elrepo.org/linux/kernel/el7/\$basearch/
	http://mirrors.coreix.net/elrepo/kernel/el7/\$basearch/
	http://jur-linux.org/download/elrepo/kernel/el7/\$basearch/
	http://repos.lax-noc.com/elrepo/kernel/el7/\$basearch/
	http://mirror.ventraip.net.au/elrepo/kernel/el7/\$basearch/
mirrorlist=http://mirrors.elrepo.org/mirrors-elrepo-kernel.el7
enabled=1
gpgcheck=1
gpgkey=https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
protect=0
EOF

yum install -y kernel-ml
yum update -y
yum upgrade -y
