apiVersion: extensions/v1beta1 
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  selector: {}
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        daemon: prom-node-exp
    spec:
      nodeSelector:
        ceph: 'true'
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - containerPort: 9090
          hostPort: 9092
          name: serverport
