apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron
  name: os-neutron
  namespace: os-neutron
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 9696
    protocol: TCP
    name: https
  selector:
    openstack-app: neutron
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron-agent
  name: neutron-agent
  namespace: os-neutron
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: neutron-agent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron-services
  name: neutron-services
  namespace: os-neutron
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: neutron-services
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron-router
  name: neutron-router
  namespace: os-neutron
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: neutron-router
