apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate
  name: os-designate
  namespace: os-designate
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 9001
    protocol: TCP
    name: https
  selector:
    openstack-app: designate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-dns
  name: designate-dns
  namespace: os-designate
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 553
    targetPort: 553
    protocol: TCP
    name: dns-tcp
  - port: 553
    targetPort: 553
    protocol: UDP
    name: dns-udp
  selector:
    openstack-app: designate-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-dns
  name: dns
  namespace: os-designate
spec:
  sessionAffinity: 'ClientIP'
  ports:
  - port: 53
    targetPort: 553
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 553
    protocol: UDP
    name: dns-udp
  selector:
    openstack-app: designate-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-dns
  name: designate-agent
  namespace: os-designate
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5358
    targetPort: 5358
    protocol: TCP
    name: agent
  selector:
    openstack-app: designate-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-mdns
  name: designate-mdns
  namespace: os-designate
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5354
    targetPort: 5354
    protocol: TCP
    name: mdns-tcp
  - port: 5354
    targetPort: 5354
    protocol: UDP
    name: mdns-udp
  selector:
    openstack-app: designate-mdns
