apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: accounts
  name: os-accounts
  namespace: os-accounts
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 4433
    protocol: TCP
    name: https
  selector:
    openstack-app: accounts
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: accounts-password
  name: os-password
  namespace: os-accounts
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 44333
    protocol: TCP
    name: https
  selector:
    openstack-app: accounts-password
