FROM %%DOCKER_NAMESPACE%%/%%DOCKER_PREFIX%%base:%%DOCKER_TAG%%
ENV OPENSTACK_COMPONENT="os-swift"

RUN yum -y install \
        openstack-swift \
        python-ceilometermiddleware \
        httpd \
        mod_wsgi \
        mod_auth_kerb \
        mod_ssl \
        git && \
    rpm -e --nodeps centos-logos && \
    rm -f /etc/httpd/conf.d/*.conf && \
    sed -i 's/^Listen 80/#Listen 80/' /etc/httpd/conf/httpd.conf && \
    git clone --depth 1 https://github.com/openstack/swiftonfile.git /opt/swiftonfile && \
    cd /opt/swiftonfile && \
      python setup.py install && \
    yum autoremove -y \
        git && \
    yum clean all && \
    mkdir -p /opt/swift

ADD ./assets /opt/harbor/assets
RUN /bin/cp -rf /opt/harbor/assets/* / && \
    chown -R swift:swift /etc/swift
