apiVersion: v1
kind: Secret
metadata:
  name: foreman-master
  namespace: os-foreman
type: Opaque
data:
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  foreman-db-name: {{FOREMAN_DB_NAME}}
  foreman-db-user: {{FOREMAN_DB_USER}}
  foreman-db-password: {{FOREMAN_DB_PASSWORD}}
  foreman-oauth-key: {{FOREMAN_OAUTH_KEY}}
  foreman-oauth-secret: {{FOREMAN_OAUTH_SECRET}}
  foreman-smtp-host: {{FOREMAN_SMTP_HOST}}
  foreman-smtp-port: {{FOREMAN_SMTP_PORT}}
  foreman-smtp-user: {{FOREMAN_SMTP_USER}}
  foreman-smtp-pass: {{FOREMAN_SMTP_PASS}}
  foreman-default-from-email: {{FOREMAN_DEFAULT_FROM_EMAIL}}
  foreman-default-admin-email: {{FOREMAN_DEFAULT_ADMIN_EMAIL}}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    openstack-app: foreman-master
    version: v0.1.0
  name: foreman-master
  namespace: os-foreman
spec:
  template:
    metadata:
      labels:
        openstack-app: foreman-master
        version: v0.1.0
      name: master
      namespace: os-foreman
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: foreman-master
          image:  docker.io/port/foreman-kube-wrapper-master:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
            - name: data
              mountPath: "/var/lib/harbor/foreman"
              readOnly: false
          securityContext:
            privileged: false
      volumes:
        - name: os-config
          secret:
            secretName: foreman-master
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: data
          persistentVolumeClaim:
            claimName: os-foreman
