apiVersion: v1
kind: Secret
metadata:
  name: foreman-proxy-{{PROXY_BRIDGE}}
  namespace: os-foreman
type: Opaque
data:
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  foreman-oauth-key: {{FOREMAN_OAUTH_KEY}}
  foreman-oauth-secret: {{FOREMAN_OAUTH_SECRET}}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    openstack-app: foreman-proxy-{{PROXY_BRIDGE}}
    version: v0.1.0
  name: foreman-proxy-{{PROXY_BRIDGE}}
  namespace: os-foreman
spec:
  template:
    metadata:
      labels:
        openstack-app: foreman-proxy-{{PROXY_BRIDGE}}
        version: v0.1.0
      name: proxy-{{PROXY_BRIDGE}}
      namespace: os-foreman
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: foreman-proxy-{{PROXY_BRIDGE}}
          image:  docker.io/port/foreman-kube-wrapper:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
            - name: PROXY_BRIDGE
              value: {{PROXY_BRIDGE}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
            - name: var-run-netns
              mountPath: /var/run/netns
              readOnly: false
            - name: var-run-openvswitch
              mountPath: /var/run/openvswitch
              readOnly: false
            - name: host-dev
              mountPath: /dev
              readOnly: false
            - name: host-run
              mountPath: /run
              readOnly: false
            - name: data
              mountPath: "/var/lib/harbor/foreman"
              readOnly: false
          securityContext:
            privileged: true
      hostPID: true
      hostNetwork: true
      volumes:
        - name: os-config
          secret:
            secretName: foreman-proxy-{{PROXY_BRIDGE}}
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: var-run-netns
          hostPath:
            path: /var/run/netns
        - name: var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-run
          hostPath:
            path: /run
        - name: data
          persistentVolumeClaim:
            claimName: os-foreman
