apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-keystone
    version: v0.1.0
  name: undercloud-keystone-adm
  namespace: node-keystone
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 35357
    targetPort: 35357
    protocol: TCP
    name: keystone-admin
  selector:
    harbor-app: undercloud-keystone
---
apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-keystone
    version: v0.1.0
  name: undercloud-keystone-pub
  namespace: node-keystone
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: keystone
  selector:
    harbor-app: undercloud-keystone
