apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: memcached
  name: memcached
  namespace: os-memcached
spec:
  clusterIP: 'None'
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
    name: memcached
  selector:
    openstack-app: memcached
