#!/bin/sh
: ${HOST_ROOT:='/host'}

install_assets () {
  echo "Installing: HarborOS"
  /bin/cp -rf /opt/host/etc/* ${HOST_ROOT}/etc/
  mkdir -p ${HOST_ROOT}/usr/local/bin
  /bin/cp -rf /opt/host/usr/local/bin/* ${HOST_ROOT}/usr/local/bin/

  echo "Finished Installation"
}

install_assets
