#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

yum -y install http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
