apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
      name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
          image: sameersbn/gitlab:8.3.2
          ports:
          - containerPort: 80
            name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
            protocol: TCP
          - containerPort: 22
            name: {{OPENSTACK_COMPONENT}}-ssh
            protocol: TCP
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}.{{OS_DOMAIN}}
            - name: TZ
              value: UTC
            - name: GITLAB_TIMEZONE
              value: UTC
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_HOST
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}.{{OS_DOMAIN}}
            - name: GITLAB_PORT
              value: "80"
            - name: GITLAB_SSH_PORT
              value: "22"
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: "true"
            - name: GITLAB_NOTIFY_PUSHER
              value: "false"
            - name: GITLAB_EMAIL
              value: notifications@{{OS_DOMAIN}}
            - name: GITLAB_EMAIL_REPLY_TO
              value: noreply@{{OS_DOMAIN}}
            - name: GITLAB_INCOMING_EMAIL_ADDRESS
              value: reply@{{OS_DOMAIN}}
            - name: GITLAB_BACKUP_SCHEDULE
              value: daily
            - name: GITLAB_BACKUP_TIME
              value: 01:00
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: os-gitlab-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: passw0rd
            - name: DB_NAME
              value: gitlab_production
            - name: REDIS_HOST
              value: os-gitlab-redis
            - name: REDIS_PORT
              value: "6379"
            - name: SMTP_ENABLED
              value: "false"
            - name: SMTP_DOMAIN
              value: {{OS_DOMAIN}}
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: mailer@{{OS_DOMAIN}}
            - name: SMTP_PASS
              value: password
            - name: SMTP_STARTTLS
              value: "true"
            - name: SMTP_AUTHENTICATION
              value: login
            - name: IMAP_ENABLED
              value: "false"
            - name: IMAP_HOST
              value: imap.gmail.com
            - name: IMAP_PORT
              value: "993"
            - name: IMAP_USER
              value: mailer@{{OS_DOMAIN}}
            - name: IMAP_PASS
              value: password
            - name: IMAP_SSL
              value: "true"
            - name: IMAP_STARTTLS
              value: "false"
            - name: LDAP_ENABLED
              value: "true"
            - name: LDAP_HOST
              value: ipa.{{OS_DOMAIN}}
            - name: LDAP_PORT
              value: "389"
            - name: LDAP_UID
              value: "uid"
            - name: LDAP_METHOD
              value: "plain"
            - name: LDAP_BIND_DN
              value: "uid=gitlab,cn=users,cn=accounts,dc=port,dc=direct"
            - name: LDAP_PASS
              value: "SuperSecret"
            - name: LDAP_ACTIVE_DIRECTORY
              value: "false"
            - name: LDAP_BASE
              value: "cn=accounts,dc=port,dc=direct"
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-data
              mountPath: "/home/git/data"
              readOnly: false
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-data
          emptyDir: {}
