apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-ssh
  labels:
    app: {{OPENSTACK_COMPONENT}}-ssh
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    name: {{OPENSTACK_COMPONENT}}-ssh
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
