apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: cockpit
    version: v0.1.0
  name: cockpit
  namespace: node-cockpit
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: cockpit
  selector:
    harbor-app: cockpit
