apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-engine-rc
      name: {{OPENSTACK_COMPONENT}}-engine
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-engine
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/heat-engine:{{OS_RELEASE}}
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-engine.{{OS_DOMAIN}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
