#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

dnf install -y openstack-trove-guestagent
