apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cinder
  name: os-cinder
  namespace: os-cinder
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8776
    protocol: TCP
    name: https
  selector:
    openstack-app: cinder
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cinder-scheduler
  name: cinder-scheduler
  namespace: os-cinder
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: cinder-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cinder-backup
  name: cinder-backup
  namespace: os-cinder
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: cinder-backup
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cinder-volume-glusterfs
  name: cinder-volume-glusterfs
  namespace: os-cinder
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: cinder-volume-glusterfs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: cinder-volume-lvm
  name: cinder-volume-lvm
  namespace: os-cinder
spec:
  clusterIP: 'None'
  ports:
  - port: 1
  selector:
    openstack-app: cinder-volume-lvm
