apiVersion: v1
kind: Secret
metadata:
  name: trove-manager
  namespace: os-trove
type: Opaque
data:
  kube-endpoint: {{KUBE_ENDPOINT}}
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  keystone-admin-token: {{KEYSTONE_ADMIN_TOKEN}}
  keystone-admin-user: {{KEYSTONE_ADMIN_USER}}
  keystone-admin-project: {{KEYSTONE_ADMIN_PROJECT}}
  keystone-admin-password: {{KEYSTONE_ADMIN_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  trove-keystone-user: {{TROVE_KEYSTONE_USER}}
  trove-keystone-password: {{TROVE_KEYSTONE_PASSWORD}}
  trove-db-name: {{TROVE_DB_NAME}}
  trove-db-user: {{TROVE_DB_USER}}
  trove-db-password: {{TROVE_DB_PASSWORD}}
  trove-rabbitmq-user: {{TROVE_RABBITMQ_USER}}
  trove-rabbitmq-password: {{TROVE_RABBITMQ_PASS}}
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: trove-manager
    version: v0.1.0
  name: trove-manager
  namespace: os-trove
spec:
  template:
    metadata:
      labels:
        openstack-app: trove-manager
        version: v0.1.0
      name: trove-manager
      namespace: os-trove
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: trove-manager
          image:  docker.io/port/trove-manager:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/ipa/ca.crt
              readOnly: true
            - name: ipa-config
              mountPath: /etc/ipa/default.conf
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config
          secret:
            secretName: trove-manager
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: ipa-config
          hostPath:
            path: /etc/ipa/default.conf
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker-ipa.sock
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: trove-image-builder
#   namespace: os-trove
# type: Opaque
# data:
#   rabbitmq-user: {{RABBITMQ_USER}}
#   rabbitmq-password: {{RABBITMQ_PASS}}
#   trove-keystone-user: {{TROVE_KEYSTONE_USER}}
#   trove-keystone-password: {{TROVE_KEYSTONE_PASSWORD}}
# ---
# apiVersion: extensions/v1beta1
# kind: Job
# metadata:
#   labels:
#     openstack-app: trove-image-builder
#     version: v0.1.0
#   name: trove-image-builder
#   namespace: os-trove
# spec:
#   template:
#     metadata:
#       labels:
#         openstack-app: trove-image-builder
#         version: v0.1.0
#       name: trove-image-builder
#       namespace: os-trove
#     spec:
#       nodeSelector:
#         freeipa: 'master'
#         arch: 'x86'
#       containers:
#         - name: trove-image-builder
#           image:  docker.io/port/trove-image-builder:latest
#           imagePullPolicy: Always
#           env:
#             - name: OS_DOMAIN
#               value: {{OS_DOMAIN}}
#           volumeMounts:
#             - name: os-config
#               mountPath: '/etc/os-config'
#               readOnly: true
#             - name: os-ssh
#               mountPath: "/etc/os-ssh"
#               readOnly: true
#             - name: ipa-ca-crt
#               mountPath: /etc/ipa/ca.crt
#               readOnly: true
#             - name: sys-fs-cgroup
#               mountPath: /sys/fs/cgroup
#               readOnly: false
#             - name: var-run-netns
#               mountPath: /var/run/netns
#               readOnly: false
#             - name: lib-modules
#               mountPath: /lib/modules
#               readOnly: true
#             - name: host-dev
#               mountPath: /dev
#               readOnly: false
#             - name: host-run
#               mountPath: /run
#               readOnly: false
#             - name: docker-binary
#               mountPath: "/bin/docker"
#               readOnly: true
#             - name: docker-socket
#               mountPath: "/var/run/docker.sock"
#               readOnly: false
#           securityContext:
#             privileged: true
#       restartPolicy: OnFailure
#       hostNetwork: true
#       volumes:
#         - name: os-config
#           secret:
#             secretName: trove-image-builder
#         - name: os-ssh
#           secret:
#             secretName: trove-ssh-secret
#         - name: ipa-ca-crt
#           hostPath:
#             path: /etc/ipa/ca.crt
#         - name: sys-fs-cgroup
#           hostPath:
#             path: /sys/fs/cgroup
#         - name: var-run-netns
#           hostPath:
#             path: /var/run/netns
#         - name: lib-modules
#           hostPath:
#             path: /lib/modules
#         - name: host-dev
#           hostPath:
#             path: /dev
#         - name: host-run
#           hostPath:
#             path: /run
#         - name: docker-binary
#           hostPath:
#             path: /usr/bin/docker
#         - name: docker-socket
#           hostPath:
#             path: /var/run/docker.sock
---
apiVersion: v1
kind: Secret
metadata:
  name: trove
  namespace: os-trove
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  trove-keystone-user: {{TROVE_KEYSTONE_USER}}
  trove-keystone-password: {{TROVE_KEYSTONE_PASSWORD}}
  trove-db-name: {{TROVE_DB_NAME}}
  trove-db-user: {{TROVE_DB_USER}}
  trove-db-password: {{TROVE_DB_PASSWORD}}
  trove-rabbitmq-user: {{TROVE_RABBITMQ_USER}}
  trove-rabbitmq-password: {{TROVE_RABBITMQ_PASS}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: trove
    version: v0.1.0
  name: trove
  namespace: os-trove
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: trove
        version: v0.1.0
      name: trove
      namespace: os-trove
    spec:
      nodeSelector:
        openstack-trove: 'true'
        arch: 'x86'
      containers:
        - name: trove-api
          image: docker.io/port/trove-api:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
        - name: trove-memcached
          image: docker.io/port/system-memcached:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "64Mi"
              cpu: "0.2"
          securityContext:
            privileged: false
        - name: trove-tls
          image: docker.io/port/haproxy-ssl-terminator:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
            - name: LOCAL_HTTP_PORT
              value: "8009"
            - name: PUBLISH_HTTPS_PORT
              value: "8779"
          ports:
          - containerPort: 8779
            name: https
            protocol: TCP
          volumeMounts:
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: trove
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: trove-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: trove-conductor
  namespace: os-trove
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  trove-keystone-user: {{TROVE_KEYSTONE_USER}}
  trove-keystone-password: {{TROVE_KEYSTONE_PASSWORD}}
  trove-db-name: {{TROVE_DB_NAME}}
  trove-db-user: {{TROVE_DB_USER}}
  trove-db-password: {{TROVE_DB_PASSWORD}}
  trove-rabbitmq-user: {{TROVE_RABBITMQ_USER}}
  trove-rabbitmq-password: {{TROVE_RABBITMQ_PASS}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: trove
    version: v0.1.0
  name: trove-conductor
  namespace: os-trove
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: trove-conductor
        version: v0.1.0
      name: trove-conductor
      namespace: os-trove
    spec:
      nodeSelector:
        openstack-trove: 'true'
        arch: 'x86'
      containers:
        - name: trove-conductor
          image: docker.io/port/trove-conductor:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: trove-conductor
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: trove-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: trove-taskmanager
  namespace: os-trove
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  trove-keystone-user: {{TROVE_KEYSTONE_USER}}
  trove-keystone-password: {{TROVE_KEYSTONE_PASSWORD}}
  trove-db-name: {{TROVE_DB_NAME}}
  trove-db-user: {{TROVE_DB_USER}}
  trove-db-password: {{TROVE_DB_PASSWORD}}
  trove-rabbitmq-user: {{TROVE_RABBITMQ_USER}}
  trove-rabbitmq-password: {{TROVE_RABBITMQ_PASS}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: trove
    version: v0.1.0
  name: trove-taskmanager
  namespace: os-trove
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: trove-taskmanager
        version: v0.1.0
      name: trove-taskmanager
      namespace: os-trove
    spec:
      nodeSelector:
        openstack-trove: 'true'
        arch: 'x86'
      containers:
        - name: trove-taskmanager
          image: docker.io/port/trove-taskmanager:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: trove-taskmanager
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: trove-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: trove-messaging-config
  namespace: os-trove
type: Opaque
data:
  trove-rabbitmq-user: {{TROVE_RABBITMQ_USER}}
  trove-rabbitmq-password: {{TROVE_RABBITMQ_PASS}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: trove-messaging
    version: v0.1.0
  name: trove-messaging
  namespace: os-trove
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: trove-messaging
        version: v0.1.0
      name: trove-messaging
      namespace: os-trove
    spec:
      nodeSelector:
        openstack-messaging: 'true'
        arch: 'x86'
      containers:
        - name: trove-messaging
          image:  docker.io/port/rabbitmq-trove:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5676
              protocol: TCP
              name: rabbitmq
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: trove-messaging-config
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
