apiVersion: v1
kind: Service
metadata:
  labels:
    harbor-app: undercloud-mariadb
    version: v0.1.0
  name: undercloud-mariadb
  namespace: node-mariadb
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    harbor-app: undercloud-mariadb
