apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
      name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/keystone-api:{{OS_RELEASE}}
          ports:
          - containerPort: 5000
            name: keystone-public
            protocol: TCP
          - containerPort: 35357
            name: keystone-admin
            protocol: TCP
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}.{{OS_DOMAIN}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  name:  {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-default-rc
      name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    spec:
      containers:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-default
          image: {{OS_REGISTRY}}/{{OS_DISTRO}}/keystone-default:{{OS_RELEASE}}
          ports:
          - containerPort: 5000
            name: keystone-public
            protocol: TCP
          - containerPort: 35357
            name: keystone-admin
            protocol: TCP
          env:
            - name: OS_HOSTNAME
              value: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-default.{{OS_DOMAIN}}
          volumeMounts:
            - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
              mountPath: "/etc/os-config"
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-config
          secret:
            secretName: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-secret
