apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  type: NodePort
  ports:
  - port: 8777
    nodePort: 8777
    name: api
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
