apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
  labels:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
spec:
  type: NodePort
  ports:
  - port: 9292
    nodePort: 9292
    name: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: {{OPENSTACK_COMPONENT}}-registry
  labels:
    app: {{OPENSTACK_COMPONENT}}-registry
spec:
  type: NodePort
  ports:
  - port: 9191
    nodePort: 9191
    name: {{OPENSTACK_COMPONENT}}-reg
    protocol: TCP
  selector:
    app: {{OPENSTACK_COMPONENT}}-{{OPENSTACK_SUBCOMPONENT}}-registry-rc
