apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova
  name: os-nova-ec2
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8773
    protocol: TCP
    name: https
  selector:
    openstack-app: nova-ec2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova
  name: os-nova
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8774
    protocol: TCP
    name: https
  selector:
    openstack-app: nova
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova
  name: os-metadata
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 80
    targetPort: 8776
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8775
    protocol: TCP
    name: https
  selector:
    openstack-app: nova-metadata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-novnc
  name: os-novnc
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 6080
    protocol: TCP
    name: https
  selector:
    openstack-app: nova-novnc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-spice
  name: os-spice
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 6082
    protocol: TCP
    name: https
  selector:
    openstack-app: nova-spice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-serial
  name: os-serial
  namespace: os-nova
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 6083
    protocol: TCP
    name: https
  selector:
    openstack-app: nova-serial
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-compute
  name: compute
  namespace: os-nova
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: nova-compute
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-compute-libvirt
  name: libvirt
  namespace: os-nova
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: nova-compute-libvirt
