apiVersion: v1
kind: Secret
metadata:
  name: heat-manager
  namespace: os-heat
type: Opaque
data:
  kube-endpoint: {{KUBE_ENDPOINT}}
  ipa-user-admin-user: {{IPA_USER_ADMIN_USER}}
  ipa-user-admin-password: {{IPA_USER_ADMIN_PASSWORD}}
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  keystone-admin-token: {{KEYSTONE_ADMIN_TOKEN}}
  keystone-admin-user: {{KEYSTONE_ADMIN_USER}}
  keystone-admin-project: {{KEYSTONE_ADMIN_PROJECT}}
  keystone-admin-password: {{KEYSTONE_ADMIN_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  heat-keystone-user: {{HEAT_KEYSTONE_USER}}
  heat-keystone-password: {{HEAT_KEYSTONE_PASSWORD}}
  heat-db-name: {{HEAT_DB_NAME}}
  heat-db-user: {{HEAT_DB_USER}}
  heat-db-password: {{HEAT_DB_PASSWORD}}
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: heat-manager
    version: v0.1.0
  name: heat-manager
  namespace: os-heat
spec:
  template:
    metadata:
      labels:
        openstack-app: heat-manager
        version: v0.1.0
      name: heat-manager
      namespace: os-heat
    spec:
      nodeSelector:
        freeipa: 'master'
        arch: 'x86'
      containers:
        - name: heat-manager
          image:  docker.io/port/heat-manager:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: '/etc/os-config'
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/ipa/ca.crt
              readOnly: true
            - name: ipa-config
              mountPath: /etc/ipa/default.conf
              readOnly: true
            - name: docker-binary
              mountPath: "/bin/docker"
              readOnly: true
            - name: docker-socket
              mountPath: "/var/run/docker.sock"
              readOnly: false
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config
          secret:
            secretName: heat-manager
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: ipa-config
          hostPath:
            path: /etc/ipa/default.conf
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker-current
        - name: docker-socket
          hostPath:
            path: /var/run/docker-ipa.sock
---
apiVersion: v1
kind: Secret
metadata:
  name: heat
  namespace: os-heat
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  heat-keystone-user: {{HEAT_KEYSTONE_USER}}
  heat-keystone-password: {{HEAT_KEYSTONE_PASSWORD}}
  heat-db-name: {{HEAT_DB_NAME}}
  heat-db-user: {{HEAT_DB_USER}}
  heat-db-password: {{HEAT_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: heat
    version: v0.1.0
  name: heat
  namespace: os-heat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: heat
        version: v0.1.0
      name: heat
      namespace: os-heat
    spec:
      nodeSelector:
        openstack-heat: 'true'
        arch: 'x86'
      containers:
        - name: heat
          image: docker.io/port/heat-api:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          ports:
          - containerPort: 8004
            name: http
            protocol: TCP
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: os-heat
              mountPath: "/var/lib/heat"
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: heat
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: heat-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: os-heat
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-cfn
  namespace: os-heat
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  heat-keystone-user: {{HEAT_KEYSTONE_USER}}
  heat-keystone-password: {{HEAT_KEYSTONE_PASSWORD}}
  heat-db-name: {{HEAT_DB_NAME}}
  heat-db-user: {{HEAT_DB_USER}}
  heat-db-password: {{HEAT_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: heat-cfn
    version: v0.1.0
  name: heat-cfn
  namespace: os-heat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: heat-cfn
        version: v0.1.0
      name: heat-cfn
      namespace: os-heat
    spec:
      nodeSelector:
        openstack-heat: 'true'
        arch: 'x86'
      containers:
        - name: heat-cfn
          image: docker.io/port/heat-api-cfn:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: os-heat
              mountPath: "/var/lib/heat"
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: heat-cfn
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: heat-cfn-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: os-heat
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-cloudwatch
  namespace: os-heat
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  heat-keystone-user: {{HEAT_KEYSTONE_USER}}
  heat-keystone-password: {{HEAT_KEYSTONE_PASSWORD}}
  heat-db-name: {{HEAT_DB_NAME}}
  heat-db-user: {{HEAT_DB_USER}}
  heat-db-password: {{HEAT_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: heat-cloudwatch
    version: v0.1.0
  name: heat-cloudwatch
  namespace: os-heat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: heat-cloudwatch
        version: v0.1.0
      name: heat-cloudwatch
      namespace: os-heat
    spec:
      nodeSelector:
        openstack-heat: 'true'
        arch: 'x86'
      containers:
        - name: heat-cloudwatch
          image: docker.io/port/heat-api-cloudwatch:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8003
            name: https
            protocol: TCP
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: os-ssl
              mountPath: "/etc/os-ssl"
              readOnly: true
            - name: os-heat
              mountPath: "/var/lib/heat"
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: heat-cloudwatch
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: os-ssl
          secret:
            secretName: heat-cloudwatch-ssl-secret
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: os-heat
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-engine
  namespace: os-heat
type: Opaque
data:
  ipa-host-admin-user: {{IPA_HOST_ADMIN_USER}}
  ipa-host-admin-password: {{IPA_HOST_ADMIN_PASSWORD}}
  mariadb-root-password: {{DB_ROOT_PASSWORD}}
  mariadb-test-database: {{MARIADB_DATABASE}}
  mariadb-test-user: {{MARIADB_USER}}
  mariadb-test-password: {{MARIADB_PASSWORD}}
  rabbitmq-user: {{RABBITMQ_USER}}
  rabbitmq-password: {{RABBITMQ_PASS}}
  heat-keystone-user: {{HEAT_KEYSTONE_USER}}
  heat-keystone-password: {{HEAT_KEYSTONE_PASSWORD}}
  heat-db-name: {{HEAT_DB_NAME}}
  heat-db-user: {{HEAT_DB_USER}}
  heat-db-password: {{HEAT_DB_PASSWORD}}
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: heat-engine
    version: v0.1.0
  name: heat-engine
  namespace: os-heat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        openstack-app: heat-engine
        version: v0.1.0
      name: heat-engine
      namespace: os-heat
    spec:
      nodeSelector:
        openstack-heat: 'true'
        arch: 'x86'
      containers:
        - name: heat-engine
          image: docker.io/port/heat-engine:latest
          imagePullPolicy: Always
          env:
            - name: OS_DOMAIN
              value: {{OS_DOMAIN}}
          volumeMounts:
            - name: os-config
              mountPath: "/etc/os-config"
              readOnly: true
            - name: os-ssl-database
              mountPath: '/etc/os-ssl-database'
              readOnly: true
            - name: os-ssl-messaging
              mountPath: '/etc/os-ssl-messaging'
              readOnly: true
            - name: ipa-ca-crt
              mountPath: /etc/pki/tls/certs/ca-bundle.crt
              readOnly: true
            - name: os-heat
              mountPath: "/var/lib/heat"
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: os-config
          secret:
            secretName: heat-engine
        - name: os-ssl-database
          hostPath:
            path: /etc/harbor/auth/host/database
        - name: os-ssl-messaging
          hostPath:
            path: /etc/harbor/auth/host/messaging
        - name: ipa-ca-crt
          hostPath:
            path: /etc/ipa/ca.crt
        - name: os-heat
          emptyDir: {}
