apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: heat
  name: os-heat
  namespace: os-heat
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8004
    protocol: TCP
    name: https
  selector:
    openstack-app: heat
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: heat-cfn
  name: os-heat-cfn
  namespace: os-heat
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: https
  selector:
    openstack-app: heat-cfn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: heat-cloudwatch
  name: os-heat-cloudwatch
  namespace: os-heat
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 443
    targetPort: 8003
    protocol: TCP
    name: https
  selector:
    openstack-app: heat-cloudwatch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: heat-engine
  name: heat-engine
  namespace: os-heat
spec:
  clusterIP: "None"
  ports:
  - port: 1
  selector:
    openstack-app: heat-engine
