#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

BASE_URL=${DIB_EPEL_MIRROR:-https://dl.fedoraproject.org/pub/epel}
case "$DISTRO_NAME" in
    rhel7|centos7)
        RELEASE=7
        RPM_URL=$BASE_URL/$RELEASE/x86_64/e/
        ;;
    *)
        echo "$DISTRO_NAME is not supported"
        exit 1
        ;;
esac
